name: pocket_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  connectivity_plus: ^2.2.1
  http: ^0.13.4
  shared_preferences: ^2.0.13
  validatorless: ^1.2.1
  mask_text_input_formatter: ^2.1.0
  fluttertoast: ^8.0.9
  dio: ^4.0.1
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/imagens/

